# Generated by Django 6.0.1 on 2026-01-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='profile_image',
        ),
    ]
